apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: go-zero-mall-order
  name: go-zero-mall-order
  namespace: zero   #一定要写名称空间
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: go-zero-mall-order
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: go-zero-mall-order
    spec:
      imagePullSecrets:
        - name: aliyun-docker-hub  #提前在项目下配置访问阿里云的账号密码
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app: go-zero-mall-order
                topologyKey: kubernetes.io/hostname
      containers:
        # - image: $REGISTRY/$ALIYUNHUB_NAMESPACE/order:SNAPSHOT-$BUILD_NUMBER
        - image: $REGISTRY/$ALIYUNHUB_NAMESPACE/order:latest
 #         readinessProbe:
 #           httpGet:
 #             path: /actuator/health
 #             port: 9002
 #           timeoutSeconds: 10
 #           failureThreshold: 30
 #           periodSeconds: 5
          imagePullPolicy: Always
          name: app
          ports:
            - containerPort: 9002
              protocol: TCP
          resources:
            limits:
              cpu: 200m
              memory: 60Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: go-zero-mall-order
  name: go-zero-mall-order
  namespace: zero
spec:
  ports:
    - name: http
      port: 9002
      protocol: TCP
      targetPort: 9002
  selector:
    app: go-zero-mall-order
  sessionAffinity: None
  type: ClusterIP